version: '3.1'

services:

  wordpress:
    image: mywp:20
    restart: always
    ports:
      - 9000:80
    environment:
      DB_HOST: db
      DB_USER: wpuser
      DB_PASSWORD: wppass
      DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
