version: '3.1'

services:

  wordpress:
    image: npwp:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      DB_HOST: db
      DB_USER: wpuser
      DB_PASSWORD: wppass
      DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  certbot:
    depends_on:
      - wordpress
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email timthecat500@gmail.com --agree-tos --no-eff-email --staging -d test09.netpeak.tech

volumes:
  wordpress:
  db:
  certbot-etc:

networks:
  app-network:
    driver: bridge

